# Generated by Django 3.0 on 2020-01-06 14:26

from django.db import migrations, models
import poker_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField(choices=[(poker_app.models.PokerCardColorType['CLUBS'], 0), (poker_app.models.PokerCardColorType['HEARTS'], 1), (poker_app.models.PokerCardColorType['SPADES'], 2), (poker_app.models.PokerCardColorType['DIAMONDS'], 3)])),
                ('value', models.IntegerField(choices=[(poker_app.models.PokerCardValueType['TWO'], 2), (poker_app.models.PokerCardValueType['THREE'], 3), (poker_app.models.PokerCardValueType['FOUR'], 4), (poker_app.models.PokerCardValueType['FIVE'], 5), (poker_app.models.PokerCardValueType['SIX'], 6), (poker_app.models.PokerCardValueType['SEVEN'], 7), (poker_app.models.PokerCardValueType['HEIGHT'], 8), (poker_app.models.PokerCardValueType['NINE'], 9), (poker_app.models.PokerCardValueType['TEN'], 10), (poker_app.models.PokerCardValueType['JACK'], 11), (poker_app.models.PokerCardValueType['QUEEN'], 12), (poker_app.models.PokerCardValueType['KING'], 13), (poker_app.models.PokerCardValueType['ACE'], 14)])),
            ],
        ),
    ]
