# Generated by Django 3.0 on 2020-01-07 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import poker_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardList', models.ManyToManyField(max_length=5, to='poker_app.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardInPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draw', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poker_app.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardList', models.ManyToManyField(max_length=2, to='poker_app.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardList', models.ManyToManyField(through='poker_app.CardInPack', to='poker_app.Card')),
            ],
        ),
        migrations.CreateModel(
            name='PokerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot', models.FloatField(default=0)),
                ('blind', models.FloatField(default=0)),
                ('state', models.IntegerField(choices=[(poker_app.models.PokerGameState['COMPULSORY_BETS'], 0), (poker_app.models.PokerGameState['PRE_FLOP'], 1), (poker_app.models.PokerGameState['FLOP'], 2), (poker_app.models.PokerGameState['TURN'], 3), (poker_app.models.PokerGameState['RIVER'], 4), (poker_app.models.PokerGameState['SHOWDOWN'], 5), (poker_app.models.PokerGameState['FINISH'], 6)])),
                ('game_round', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='poker_app.Board')),
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='poker_app.Pack')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('money', models.FloatField()),
                ('online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.FloatField()),
                ('in_game', models.BooleanField(default=False)),
                ('is_dealer', models.BooleanField(default=False)),
                ('is_turn', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_app.PokerGame')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poker_app.Hand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poker_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='pokergame',
            name='userList',
            field=models.ManyToManyField(through='poker_app.UserInGame', to='poker_app.User'),
        ),
        migrations.AddField(
            model_name='cardinpack',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_app.Pack'),
        ),
    ]
