# Generated by Django 3.0 on 2020-01-07 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0002_auto_20200107_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cardList',
            field=models.ManyToManyField(blank=True, to='poker_app.Card'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='cardList',
            field=models.ManyToManyField(blank=True, to='poker_app.Card'),
        ),
        migrations.AlterField(
            model_name='pokergame',
            name='game_round',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
